// <auto-generated />
using System;
using BlazorApp02.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp02.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20240130114329_intial")]
    partial class intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("BlazorApp02.Data.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("84332f21-fd87-491b-860b-92ec517eb40c"),
                            Email = "Andy89@hotmail.com",
                            FirstName = "Andy",
                            LastName = "Ullrich",
                            Phone = "576-849-2134 x477",
                            RegistrationNo = "EG/2046/06161"
                        },
                        new
                        {
                            Id = new Guid("98bd57c5-6cc9-469d-88bf-bafcabe02e9c"),
                            Email = "Tony.Schuster34@gmail.com",
                            FirstName = "Tony",
                            LastName = "Schuster",
                            Phone = "852.261.5868 x63261",
                            RegistrationNo = "EG/2043/03142"
                        },
                        new
                        {
                            Id = new Guid("2162a334-6c40-4e4d-a0ba-9512959f1775"),
                            Email = "Kenna26@hotmail.com",
                            FirstName = "Kenna",
                            LastName = "Lindgren",
                            Phone = "448-899-1270 x23119",
                            RegistrationNo = "EG/2040/03562"
                        },
                        new
                        {
                            Id = new Guid("97e660ac-1d40-41ef-ba81-87505d8aab0e"),
                            Email = "Myrtis.Boyle@gmail.com",
                            FirstName = "Myrtis",
                            LastName = "Boyle",
                            Phone = "951.949.9045",
                            RegistrationNo = "EG/2033/06269"
                        },
                        new
                        {
                            Id = new Guid("46c42434-d9a1-4924-8f3b-95fc04ae276d"),
                            Email = "Hyman.Moore@gmail.com",
                            FirstName = "Hyman",
                            LastName = "Moore",
                            Phone = "(832) 278-5314 x081",
                            RegistrationNo = "EG/2048/06248"
                        },
                        new
                        {
                            Id = new Guid("4630c8d0-3ce9-4f72-a4bf-5aa8002de602"),
                            Email = "Darrell48@hotmail.com",
                            FirstName = "Darrell",
                            LastName = "Bruen",
                            Phone = "599.533.5637",
                            RegistrationNo = "EG/2040/04154"
                        },
                        new
                        {
                            Id = new Guid("2718e11a-a30e-40d3-9c5e-d19991faede2"),
                            Email = "Ottis.Gutmann@yahoo.com",
                            FirstName = "Ottis",
                            LastName = "Gutmann",
                            Phone = "1-856-988-6512 x15183",
                            RegistrationNo = "EG/2020/01224"
                        },
                        new
                        {
                            Id = new Guid("739d051d-18b9-45b8-b9d4-cd93589133a3"),
                            Email = "Lucie46@yahoo.com",
                            FirstName = "Lucie",
                            LastName = "Hahn",
                            Phone = "1-737-411-0185 x85705",
                            RegistrationNo = "EG/2025/02400"
                        },
                        new
                        {
                            Id = new Guid("278d77d9-ac29-4b1e-8e95-1f375b7086ed"),
                            Email = "Bret14@hotmail.com",
                            FirstName = "Bret",
                            LastName = "Franecki",
                            Phone = "909.701.5955",
                            RegistrationNo = "EG/2031/04851"
                        },
                        new
                        {
                            Id = new Guid("d479fd97-faa8-4a72-93b1-e5b5c0d06e43"),
                            Email = "Ida23@yahoo.com",
                            FirstName = "Ida",
                            LastName = "Cummings",
                            Phone = "663-363-5768 x47281",
                            RegistrationNo = "EG/2035/03921"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
