// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MudBlazorWebApp1.Data;

#nullable disable

namespace MudBlazorWebApp1.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20240130123045_intial")]
    partial class intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("MudBlazorWebApp1.Data.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("79834c26-96d7-4fe8-af94-27029f76da39"),
                            Email = "Cody_Mohr23@yahoo.com",
                            FirstName = "Cody",
                            LastName = "Mohr",
                            Phone = "(934) 721-6089 x90964",
                            RegistrationNo = "EG/2033/06289"
                        },
                        new
                        {
                            Id = new Guid("d629ad15-621c-43ac-a4bb-68ef73de62bd"),
                            Email = "Bridgette2@yahoo.com",
                            FirstName = "Bridgette",
                            LastName = "Douglas",
                            Phone = "(541) 905-6598 x08424",
                            RegistrationNo = "EG/2039/04464"
                        },
                        new
                        {
                            Id = new Guid("a9dd38a2-596a-4818-9ddc-126d0ac373e0"),
                            Email = "Karen99@hotmail.com",
                            FirstName = "Karen",
                            LastName = "Turner",
                            Phone = "(824) 677-2078 x5293",
                            RegistrationNo = "EG/2043/01705"
                        },
                        new
                        {
                            Id = new Guid("0be9a42e-7e2f-4611-85ab-a00ba7da4b91"),
                            Email = "Mose_Powlowski@yahoo.com",
                            FirstName = "Mose",
                            LastName = "Powlowski",
                            Phone = "641.652.9868 x174",
                            RegistrationNo = "EG/2026/06713"
                        },
                        new
                        {
                            Id = new Guid("f2f460ea-9ef0-43cb-a940-a339f014fa81"),
                            Email = "Adolphus49@hotmail.com",
                            FirstName = "Adolphus",
                            LastName = "Wisozk",
                            Phone = "(641) 962-6741 x8055",
                            RegistrationNo = "EG/2034/01081"
                        },
                        new
                        {
                            Id = new Guid("ed93b810-3d0b-4ac6-83cf-037358f78146"),
                            Email = "Kristian_Ondricka@hotmail.com",
                            FirstName = "Kristian",
                            LastName = "Ondricka",
                            Phone = "(667) 433-9721 x41222",
                            RegistrationNo = "EG/2042/03737"
                        },
                        new
                        {
                            Id = new Guid("5749f93a-ee1d-4426-9b13-03ea75c588f5"),
                            Email = "Ellsworth.Lockman79@hotmail.com",
                            FirstName = "Ellsworth",
                            LastName = "Lockman",
                            Phone = "774.403.5267",
                            RegistrationNo = "EG/2046/01959"
                        },
                        new
                        {
                            Id = new Guid("4e21b396-ed87-44c3-a154-00574799bf27"),
                            Email = "America_Hermiston@gmail.com",
                            FirstName = "America",
                            LastName = "Hermiston",
                            Phone = "559.505.6362",
                            RegistrationNo = "EG/2028/01479"
                        },
                        new
                        {
                            Id = new Guid("a5845fba-f35d-4942-9c5f-e4943d28ecec"),
                            Email = "Lynn.Witting@hotmail.com",
                            FirstName = "Lynn",
                            LastName = "Witting",
                            Phone = "1-994-432-9981 x3685",
                            RegistrationNo = "EG/2042/01137"
                        },
                        new
                        {
                            Id = new Guid("422350c1-82a3-4bae-80e1-e0eab10175de"),
                            Email = "Eriberto_Bosco@gmail.com",
                            FirstName = "Eriberto",
                            LastName = "Bosco",
                            Phone = "(639) 834-0332 x739",
                            RegistrationNo = "EG/2024/06099"
                        },
                        new
                        {
                            Id = new Guid("446a0f73-be2e-488f-85b0-2e3bd4a17838"),
                            Email = "Perry.McClure25@yahoo.com",
                            FirstName = "Perry",
                            LastName = "McClure",
                            Phone = "624.951.2400",
                            RegistrationNo = "EG/2030/07024"
                        },
                        new
                        {
                            Id = new Guid("6ae24a9e-e14b-43d1-8a35-e4480cf20e79"),
                            Email = "Orrin_Morissette@yahoo.com",
                            FirstName = "Orrin",
                            LastName = "Morissette",
                            Phone = "1-557-672-0907",
                            RegistrationNo = "EG/2044/05709"
                        },
                        new
                        {
                            Id = new Guid("e05c153c-4de7-4cb3-99f7-6f34bbafb5cf"),
                            Email = "Wava.Vandervort87@hotmail.com",
                            FirstName = "Wava",
                            LastName = "Vandervort",
                            Phone = "(228) 306-2123 x9207",
                            RegistrationNo = "EG/2033/08281"
                        },
                        new
                        {
                            Id = new Guid("bd000c96-4cf2-4572-9fff-f7338010ef44"),
                            Email = "Daniella.Pollich@hotmail.com",
                            FirstName = "Daniella",
                            LastName = "Pollich",
                            Phone = "526-266-3300",
                            RegistrationNo = "EG/2032/02776"
                        },
                        new
                        {
                            Id = new Guid("5722c181-0e52-4569-bec7-9ed15ed001a1"),
                            Email = "Rylee_Kilback@hotmail.com",
                            FirstName = "Rylee",
                            LastName = "Kilback",
                            Phone = "703-769-3203 x8610",
                            RegistrationNo = "EG/2023/02290"
                        },
                        new
                        {
                            Id = new Guid("8d90510a-38a0-4c7b-9b7c-88ce3a2ae915"),
                            Email = "Kristian49@hotmail.com",
                            FirstName = "Kristian",
                            LastName = "Fadel",
                            Phone = "889.797.8586",
                            RegistrationNo = "EG/2050/09133"
                        },
                        new
                        {
                            Id = new Guid("58719496-4bfa-4fb7-8bf7-345edecb1302"),
                            Email = "Ana.Jenkins4@hotmail.com",
                            FirstName = "Ana",
                            LastName = "Jenkins",
                            Phone = "(924) 553-9521",
                            RegistrationNo = "EG/2029/04412"
                        },
                        new
                        {
                            Id = new Guid("594cbfb7-308b-43fd-afc8-bda89868a3bc"),
                            Email = "Dayna58@yahoo.com",
                            FirstName = "Dayna",
                            LastName = "Grimes",
                            Phone = "890.838.5650 x1016",
                            RegistrationNo = "EG/2038/07756"
                        },
                        new
                        {
                            Id = new Guid("726de089-3056-4bbb-9d43-9a5167e44559"),
                            Email = "Hillary_McClure@gmail.com",
                            FirstName = "Hillary",
                            LastName = "McClure",
                            Phone = "1-914-349-4180 x7917",
                            RegistrationNo = "EG/2023/06059"
                        },
                        new
                        {
                            Id = new Guid("7f83b2fc-1481-4db4-a8af-4a36d1299842"),
                            Email = "Jaida_Klocko13@yahoo.com",
                            FirstName = "Jaida",
                            LastName = "Klocko",
                            Phone = "573.356.2893 x299",
                            RegistrationNo = "EG/2034/01573"
                        },
                        new
                        {
                            Id = new Guid("08f600cf-f767-4ae7-8063-fb5fc8e51979"),
                            Email = "Jacinto_DAmore@yahoo.com",
                            FirstName = "Jacinto",
                            LastName = "D'Amore",
                            Phone = "366.537.2044",
                            RegistrationNo = "EG/2050/02968"
                        },
                        new
                        {
                            Id = new Guid("1b8a4646-69d3-44c4-8914-fba1e906c64c"),
                            Email = "Malcolm_Kessler@hotmail.com",
                            FirstName = "Malcolm",
                            LastName = "Kessler",
                            Phone = "(491) 579-8971 x05976",
                            RegistrationNo = "EG/2042/03290"
                        },
                        new
                        {
                            Id = new Guid("a265bf77-3ff7-4a7c-ac87-b38ba6db3008"),
                            Email = "Serena_Hirthe@gmail.com",
                            FirstName = "Serena",
                            LastName = "Hirthe",
                            Phone = "441-331-3301",
                            RegistrationNo = "EG/2025/02687"
                        },
                        new
                        {
                            Id = new Guid("e0daac4f-5c3e-484c-aaff-4f0092924a04"),
                            Email = "Nola.Wiegand@hotmail.com",
                            FirstName = "Nola",
                            LastName = "Wiegand",
                            Phone = "1-632-792-5345 x61545",
                            RegistrationNo = "EG/2037/06555"
                        },
                        new
                        {
                            Id = new Guid("3dc8d548-2c50-4049-a8a1-c7f45e5488b0"),
                            Email = "Jerald_Rosenbaum99@gmail.com",
                            FirstName = "Jerald",
                            LastName = "Rosenbaum",
                            Phone = "(660) 889-0394",
                            RegistrationNo = "EG/2037/05622"
                        },
                        new
                        {
                            Id = new Guid("439f7f45-cc6d-48c7-822a-e20b8c5cacdd"),
                            Email = "Alvah89@hotmail.com",
                            FirstName = "Alvah",
                            LastName = "Bins",
                            Phone = "480.965.2228",
                            RegistrationNo = "EG/2026/03032"
                        },
                        new
                        {
                            Id = new Guid("70d768a3-cd65-4b21-b180-512ebfb6258e"),
                            Email = "Lon15@gmail.com",
                            FirstName = "Lon",
                            LastName = "Bruen",
                            Phone = "216-669-2788 x337",
                            RegistrationNo = "EG/2032/07393"
                        },
                        new
                        {
                            Id = new Guid("9d3645bf-b78c-4703-b8c0-a6844dcf1deb"),
                            Email = "Nona.Streich@gmail.com",
                            FirstName = "Nona",
                            LastName = "Streich",
                            Phone = "698-832-7384 x0188",
                            RegistrationNo = "EG/2034/05338"
                        },
                        new
                        {
                            Id = new Guid("74758780-a38c-4cca-aa0b-7a2225f7ee95"),
                            Email = "Vita72@gmail.com",
                            FirstName = "Vita",
                            LastName = "Heaney",
                            Phone = "1-607-948-9580 x2456",
                            RegistrationNo = "EG/2027/03024"
                        },
                        new
                        {
                            Id = new Guid("72a3b15e-b804-41e8-aca1-5a46361a5724"),
                            Email = "Mara.Toy15@gmail.com",
                            FirstName = "Mara",
                            LastName = "Toy",
                            Phone = "974-391-5455 x10928",
                            RegistrationNo = "EG/2041/01926"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
